argo-cd:  
  global:
    domain: argo.roussev.com

  configs:
    params:
      server.insecure: "true"

  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
      hostname: argo.roussev.com
      path: /
      pathType: Prefix
      tls: true
    
    certificate:
      enabled: true
      domain: argo.roussev.com
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-prod